var annotated_dup =
[
    [ "chira", null, [
      [ "Device", null, [
        [ "WindowHandle", "d7/d15/structchira_1_1_device_1_1_window_handle.html", "d7/d15/structchira_1_1_device_1_1_window_handle" ]
      ] ],
      [ "Input", null, [
        [ "Event", "d9/df5/classchira_1_1_input_1_1_event.html", "d9/df5/classchira_1_1_input_1_1_event" ]
      ] ],
      [ "Renderer", "d5/d36/namespacechira_1_1_renderer.html", [
        [ "TextureHandle", "dd/d4f/structchira_1_1_renderer_1_1_texture_handle.html", "dd/d4f/structchira_1_1_renderer_1_1_texture_handle" ],
        [ "FrameBufferHandle", "dc/d29/structchira_1_1_renderer_1_1_frame_buffer_handle.html", "dc/d29/structchira_1_1_renderer_1_1_frame_buffer_handle" ],
        [ "ShaderModuleHandle", "dd/db1/structchira_1_1_renderer_1_1_shader_module_handle.html", "dd/db1/structchira_1_1_renderer_1_1_shader_module_handle" ],
        [ "ShaderHandle", "d8/db3/structchira_1_1_renderer_1_1_shader_handle.html", "d8/db3/structchira_1_1_renderer_1_1_shader_handle" ],
        [ "UniformBufferHandle", "df/d5c/structchira_1_1_renderer_1_1_uniform_buffer_handle.html", "df/d5c/structchira_1_1_renderer_1_1_uniform_buffer_handle" ],
        [ "MeshHandle", "d4/d52/structchira_1_1_renderer_1_1_mesh_handle.html", "d4/d52/structchira_1_1_renderer_1_1_mesh_handle" ]
      ] ],
      [ "Steam", null, [
        [ "CallbackMessage", "db/d2c/structchira_1_1_steam_1_1_callback_message.html", "db/d2c/structchira_1_1_steam_1_1_callback_message" ],
        [ "Callbacks", "d4/d13/structchira_1_1_steam_1_1_callbacks.html", [
          [ "Completed", "d7/d7f/structchira_1_1_steam_1_1_callbacks_1_1_completed.html", "d7/d7f/structchira_1_1_steam_1_1_callbacks_1_1_completed" ],
          [ "DLCInstalled", "dc/d84/structchira_1_1_steam_1_1_callbacks_1_1_d_l_c_installed.html", "dc/d84/structchira_1_1_steam_1_1_callbacks_1_1_d_l_c_installed" ],
          [ "FileDetailsResult", "df/dae/structchira_1_1_steam_1_1_callbacks_1_1_file_details_result.html", "df/dae/structchira_1_1_steam_1_1_callbacks_1_1_file_details_result" ],
          [ "GameOverlayActivated", "d1/d12/structchira_1_1_steam_1_1_callbacks_1_1_game_overlay_activated.html", "d1/d12/structchira_1_1_steam_1_1_callbacks_1_1_game_overlay_activated" ]
        ] ]
      ] ],
      [ "ConEntry", "dc/dd3/classchira_1_1_con_entry.html", "dc/dd3/classchira_1_1_con_entry" ],
      [ "ConCommand", "d0/d61/classchira_1_1_con_command.html", "d0/d61/classchira_1_1_con_command" ],
      [ "ConEntryRegistry", "de/d90/classchira_1_1_con_entry_registry.html", "de/d90/classchira_1_1_con_entry_registry" ],
      [ "ConVar", "db/dc4/classchira_1_1_con_var.html", "db/dc4/classchira_1_1_con_var" ],
      [ "ConCommandRef", "da/d77/classchira_1_1_con_command_ref.html", "da/d77/classchira_1_1_con_command_ref" ],
      [ "ConVarRef", "d6/d84/classchira_1_1_con_var_ref.html", "d6/d84/classchira_1_1_con_var_ref" ],
      [ "Engine", "d6/d8e/classchira_1_1_engine.html", "d6/d8e/classchira_1_1_engine" ],
      [ "Logger", "d5/df6/classchira_1_1_logger.html", "d5/df6/classchira_1_1_logger" ],
      [ "LogChannel", "da/d25/classchira_1_1_log_channel.html", "da/d25/classchira_1_1_log_channel" ],
      [ "AudioNoiseComponent", "db/d3d/structchira_1_1_audio_noise_component.html", "db/d3d/structchira_1_1_audio_noise_component" ],
      [ "AudioSfxrComponent", "dd/dd9/structchira_1_1_audio_sfxr_component.html", "dd/dd9/structchira_1_1_audio_sfxr_component" ],
      [ "AudioSpeechComponent", "df/daf/structchira_1_1_audio_speech_component.html", "df/daf/structchira_1_1_audio_speech_component" ],
      [ "AudioWavComponent", "d7/dbe/structchira_1_1_audio_wav_component.html", "d7/dbe/structchira_1_1_audio_wav_component" ],
      [ "AudioWavStreamComponent", "d5/de9/structchira_1_1_audio_wav_stream_component.html", "d5/de9/structchira_1_1_audio_wav_stream_component" ],
      [ "BillboardComponent", "d4/d76/structchira_1_1_billboard_component.html", "d4/d76/structchira_1_1_billboard_component" ],
      [ "CameraComponent", "dd/dae/structchira_1_1_camera_component.html", "dd/dae/structchira_1_1_camera_component" ],
      [ "LayerComponent", "d0/dc8/structchira_1_1_layer_component.html", null ],
      [ "DirectionalLightComponent", "d1/de2/structchira_1_1_directional_light_component.html", "d1/de2/structchira_1_1_directional_light_component" ],
      [ "PointLightComponent", "df/d2a/structchira_1_1_point_light_component.html", "df/d2a/structchira_1_1_point_light_component" ],
      [ "SpotLightComponent", "df/d16/structchira_1_1_spot_light_component.html", "df/d16/structchira_1_1_spot_light_component" ],
      [ "MeshComponent", "d6/d8e/structchira_1_1_mesh_component.html", "d6/d8e/structchira_1_1_mesh_component" ],
      [ "MeshDynamicComponent", "d8/dec/structchira_1_1_mesh_dynamic_component.html", "d8/dec/structchira_1_1_mesh_dynamic_component" ],
      [ "MeshSpriteComponent", "da/d14/structchira_1_1_mesh_sprite_component.html", "da/d14/structchira_1_1_mesh_sprite_component" ],
      [ "NameComponent", "d9/d38/structchira_1_1_name_component.html", "d9/d38/structchira_1_1_name_component" ],
      [ "SkyboxComponent", "d3/d21/structchira_1_1_skybox_component.html", "d3/d21/structchira_1_1_skybox_component" ],
      [ "NoRenderTagComponent", "d5/d45/structchira_1_1_no_render_tag_component.html", null ],
      [ "SceneTagComponent", "db/dc6/structchira_1_1_scene_tag_component.html", null ],
      [ "TransformComponent", "d3/de7/structchira_1_1_transform_component.html", "d3/de7/structchira_1_1_transform_component" ],
      [ "UUIDComponent", "d5/d80/structchira_1_1_u_u_i_d_component.html", "d5/d80/structchira_1_1_u_u_i_d_component" ],
      [ "Entity", "de/dca/classchira_1_1_entity.html", "de/dca/classchira_1_1_entity" ],
      [ "Scene", "d5/db7/classchira_1_1_scene.html", "d5/db7/classchira_1_1_scene" ],
      [ "Viewport", "db/dcc/classchira_1_1_viewport.html", "db/dcc/classchira_1_1_viewport" ],
      [ "TranslationFileResource", "d7/d6b/classchira_1_1_translation_file_resource.html", "d7/d6b/classchira_1_1_translation_file_resource" ],
      [ "TranslationManager", "dc/d59/classchira_1_1_translation_manager.html", null ],
      [ "Image", "dd/d6f/classchira_1_1_image.html", "dd/d6f/classchira_1_1_image" ],
      [ "ChiraMeshLoader", "d7/d5f/classchira_1_1_chira_mesh_loader.html", "d7/d5f/classchira_1_1_chira_mesh_loader" ],
      [ "ChiraMeshHeader", "d4/db5/structchira_1_1_chira_mesh_header.html", "d4/db5/structchira_1_1_chira_mesh_header" ],
      [ "IMeshLoader", "dd/dec/classchira_1_1_i_mesh_loader.html", "dd/dec/classchira_1_1_i_mesh_loader" ],
      [ "OBJMeshLoader", "dd/d84/classchira_1_1_o_b_j_mesh_loader.html", "dd/d84/classchira_1_1_o_b_j_mesh_loader" ],
      [ "ISettingsLoader", "d0/d1a/classchira_1_1_i_settings_loader.html", "d0/d1a/classchira_1_1_i_settings_loader" ],
      [ "JSONSettingsLoader", "d0/dbd/classchira_1_1_j_s_o_n_settings_loader.html", "d0/dbd/classchira_1_1_j_s_o_n_settings_loader" ],
      [ "ColorR", "db/d16/structchira_1_1_color_r.html", "db/d16/structchira_1_1_color_r" ],
      [ "ColorRG", "d5/d75/structchira_1_1_color_r_g.html", "d5/d75/structchira_1_1_color_r_g" ],
      [ "ColorRGB", "d2/df6/structchira_1_1_color_r_g_b.html", "d2/df6/structchira_1_1_color_r_g_b" ],
      [ "ColorRGBA", "d2/dd4/structchira_1_1_color_r_g_b_a.html", "d2/dd4/structchira_1_1_color_r_g_b_a" ],
      [ "UnweightedDirectedGraph", "d5/df9/classchira_1_1_unweighted_directed_graph.html", "d5/df9/classchira_1_1_unweighted_directed_graph" ],
      [ "Vertex", "d6/df6/structchira_1_1_vertex.html", "d6/df6/structchira_1_1_vertex" ],
      [ "DiscordButtonData", "de/d6f/structchira_1_1_discord_button_data.html", "de/d6f/structchira_1_1_discord_button_data" ],
      [ "IModule", "d7/d77/structchira_1_1_i_module.html", "d7/d77/structchira_1_1_i_module" ],
      [ "MaterialCubemap", "dc/d74/classchira_1_1_material_cubemap.html", "dc/d74/classchira_1_1_material_cubemap" ],
      [ "IMaterial", "df/d5f/classchira_1_1_i_material.html", "df/d5f/classchira_1_1_i_material" ],
      [ "MaterialFrameBuffer", "d3/d3c/classchira_1_1_material_frame_buffer.html", "d3/d3c/classchira_1_1_material_frame_buffer" ],
      [ "MaterialPhong", "d8/da4/classchira_1_1_material_phong.html", "d8/da4/classchira_1_1_material_phong" ],
      [ "MaterialTextured", "d6/d69/classchira_1_1_material_textured.html", "d6/d69/classchira_1_1_material_textured" ],
      [ "MaterialUntextured", "d9/d2f/classchira_1_1_material_untextured.html", "d9/d2f/classchira_1_1_material_untextured" ],
      [ "MeshData", "d7/de1/classchira_1_1_mesh_data.html", "d7/de1/classchira_1_1_mesh_data" ],
      [ "MeshDataBuilder", "de/da0/classchira_1_1_mesh_data_builder.html", "de/da0/classchira_1_1_mesh_data_builder" ],
      [ "MeshDataResource", "de/de7/classchira_1_1_mesh_data_resource.html", "de/de7/classchira_1_1_mesh_data_resource" ],
      [ "Shader", "d2/d71/classchira_1_1_shader.html", "d2/d71/classchira_1_1_shader" ],
      [ "UniformBufferObject", "dd/db8/classchira_1_1_uniform_buffer_object.html", "dd/db8/classchira_1_1_uniform_buffer_object" ],
      [ "PerspectiveViewUBO", "d8/db0/structchira_1_1_perspective_view_u_b_o.html", "d8/db0/structchira_1_1_perspective_view_u_b_o" ],
      [ "LightsUBO", "da/dad/structchira_1_1_lights_u_b_o.html", "da/dad/structchira_1_1_lights_u_b_o" ],
      [ "ITexture", "da/dcb/classchira_1_1_i_texture.html", "da/dcb/classchira_1_1_i_texture" ],
      [ "Texture", "d4/d36/classchira_1_1_texture.html", "d4/d36/classchira_1_1_texture" ],
      [ "TextureCubemap", "d6/d75/classchira_1_1_texture_cubemap.html", "d6/d75/classchira_1_1_texture_cubemap" ],
      [ "BinaryResource", "dd/dba/classchira_1_1_binary_resource.html", "dd/dba/classchira_1_1_binary_resource" ],
      [ "JSONResource", "d4/daa/classchira_1_1_j_s_o_n_resource.html", "d4/daa/classchira_1_1_j_s_o_n_resource" ],
      [ "FilesystemResourceProvider", "de/de0/classchira_1_1_filesystem_resource_provider.html", "de/de0/classchira_1_1_filesystem_resource_provider" ],
      [ "IResourceProvider", "dc/da5/classchira_1_1_i_resource_provider.html", "dc/da5/classchira_1_1_i_resource_provider" ],
      [ "Resource", "d8/d5c/classchira_1_1_resource.html", "d8/d5c/classchira_1_1_resource" ],
      [ "StringResource", "d3/d87/classchira_1_1_string_resource.html", "d3/d87/classchira_1_1_string_resource" ],
      [ "ConsolePanel", "de/d17/classchira_1_1_console_panel.html", "de/d17/classchira_1_1_console_panel" ],
      [ "ResourceUsageTrackerPanel", "d5/dc8/classchira_1_1_resource_usage_tracker_panel.html", "d5/dc8/classchira_1_1_resource_usage_tracker_panel" ],
      [ "Font", "db/d45/classchira_1_1_font.html", "db/d45/classchira_1_1_font" ],
      [ "IPanel", "df/dde/classchira_1_1_i_panel.html", "df/dde/classchira_1_1_i_panel" ],
      [ "IViewportPanel", "d7/dea/classchira_1_1_i_viewport_panel.html", "d7/dea/classchira_1_1_i_viewport_panel" ],
      [ "AbstractFactory", "d6/dfd/classchira_1_1_abstract_factory.html", "d6/dfd/classchira_1_1_abstract_factory" ],
      [ "DependencyGraph", "d2/d56/classchira_1_1_dependency_graph.html", "d2/d56/classchira_1_1_dependency_graph" ],
      [ "NoCopy", "d5/dce/structchira_1_1_no_copy.html", "d5/dce/structchira_1_1_no_copy" ],
      [ "NoMove", "d1/d28/structchira_1_1_no_move.html", "d1/d28/structchira_1_1_no_move" ],
      [ "NoCopyOrMove", "d4/ddf/structchira_1_1_no_copy_or_move.html", "d4/ddf/structchira_1_1_no_copy_or_move" ],
      [ "SharedPointerMetadata", "d9/d83/structchira_1_1_shared_pointer_metadata.html", "d9/d83/structchira_1_1_shared_pointer_metadata" ],
      [ "SharedPointer", "d4/d08/classchira_1_1_shared_pointer.html", "d4/d08/classchira_1_1_shared_pointer" ],
      [ "TypeStringBase", "de/d6e/structchira_1_1_type_string_base.html", "de/d6e/structchira_1_1_type_string_base" ],
      [ "TypeString", "d6/d8d/structchira_1_1_type_string.html", "d6/d8d/structchira_1_1_type_string" ],
      [ "TypeString< const T >", "d9/dcd/structchira_1_1_type_string_3_01const_01_t_01_4.html", "d9/dcd/structchira_1_1_type_string_3_01const_01_t_01_4" ],
      [ "TypeString< T * >", "d9/dc3/structchira_1_1_type_string_3_01_t_01_5_01_4.html", "d9/dc3/structchira_1_1_type_string_3_01_t_01_5_01_4" ],
      [ "TypeString< T & >", "d9/dda/structchira_1_1_type_string_3_01_t_01_6_01_4.html", "d9/dda/structchira_1_1_type_string_3_01_t_01_6_01_4" ],
      [ "TypeString< const T & >", "d7/db0/structchira_1_1_type_string_3_01const_01_t_01_6_01_4.html", "d7/db0/structchira_1_1_type_string_3_01const_01_t_01_6_01_4" ],
      [ "TypeString< std::string >", "da/d69/structchira_1_1_type_string_3_01std_1_1string_01_4.html", "da/d69/structchira_1_1_type_string_3_01std_1_1string_01_4" ],
      [ "TypeString< R(ArgTypes...)>", "d5/d1d/structchira_1_1_type_string_3_01_r_07_arg_types_8_8_8_08_4.html", "d5/d1d/structchira_1_1_type_string_3_01_r_07_arg_types_8_8_8_08_4" ],
      [ "TypeString< R(*)(ArgTypes...)>", "df/dd9/structchira_1_1_type_string_3_01_r_07_5_08_07_arg_types_8_8_8_08_4.html", "df/dd9/structchira_1_1_type_string_3_01_r_07_5_08_07_arg_types_8_8_8_08_4" ],
      [ "UUIDGenerator", "db/d04/classchira_1_1_u_u_i_d_generator.html", null ]
    ] ]
];