#ifndef BASICGAMEENGINE_IMGUICONFIG_H
#define BASICGAMEENGINE_IMGUICONFIG_H


#if RELEASE
#define IMGUI_DISABLE_DEMO_WINDOWS
#define IMGUI_DISABLE_METRICS_WINDOW
#endif


#endif //BASICGAMEENGINE_IMGUICONFIG_H
